version: '3.7'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: experiment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  apache:
    image: httpd:latest
    ports:
      - "8080:80" 
    volumes:
      - ./apache-config:/usr/local/apache2/conf 

  web-server:
    build:
      context: ./app 
    depends_on:
      - db
      - apache
    ports:
      - "8001:8001"
    mem_limit: 2g
    cpus: 2
    command: sh -c "sleep 10 && python app.py"
